author: Siceron
description: Bad Bot
main: badbot.main.BadBot
name: BadBot
version: 0.4

commands:
   badbot:
      description: Nom de l'auteur
   badbot interval [secondes]:
      description: change l'intervalle entre chaque spam
   badbot kick [true/false]:
      description: change si le joueur est kick ou non pour spam
   badbot mute:
      description: mute/unmute le chat general
   badbot addblacklist [mot]:
      description: ajoute un mot a la blacklist
   badbot addblacklist [mot]:
      description: retire un mot de la blacklist

permissions:
   badbot.spam:
      description: Permet au joueur de changer les config du spam
      default: op
   badbot.spamperm:
      description: Permet au joueur de spam
      default: op
   badbot.blacklist:
      description: Permet au joueur modifier la blacklist
      default: op
   badbot.mute:
      description: Permet au joueur de mute le chat
      default: op
   badbot.muteperm:
      description: Permet au joueur de parler lors d'un mute
      default: op